# Generated by Django 4.2.3 on 2023-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booksmith", "0002_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="book",
            field=models.ManyToManyField(to="booksmith.book"),
        ),
    ]
